name: Execution Performance

on:
  workflow_dispatch:
    inputs:
      testSuite:
        type: string
        description: 'TestSuite'
        required: true
        default: 'com.mojix.bootcamp.performance.GetTest'
      concurrent:
        type: string
        description: 'Quantity of users'
        required: true
        default: '2'

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  execpokemonapi:
    runs-on: ubuntu-latest
    name: Execution Performance
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Execute test
        run: gradle gatlingRun --simulation=${{ inputs.testSuite }} -DconcurrentUsers=${{ inputs.concurrent }}

      - name: Save report
        if: ${{always()}}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: gatling report
          path: ./build/reports/gatling

      - name: "Publish Test Results"
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './build/reports/gatling'
          keep_files: true
          user_name: maurovelasco
          user_email: mauro.velasco@gmail.com
          publish_branch: gh_page

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh_page
          PUBLISH_DIR: ./build/reports/gatling
